---
kind: pipeline
name: CurrentCost InfluxDB ARM pipeline

steps:
- name: build
  image: rust:1.40
  environment:
    CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
    CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER: arm-linux-gnueabihf-gcc
    PKG_CONFIG_ALLOW_CROSS: 1
  commands:
    - dpkg --add-architecture armhf
    - apt-get update
    - apt-get install -y pkg-config libssl-dev libudev-dev
    - apt-get install -y --no-install-recommends g++-aarch64-linux-gnu libc6-dev-arm64-cross
    - rustup target add aarch64-unknown-linux-gnu
    - apt-get install -y --no-install-recommends g++-arm-linux-gnueabihf libc6-dev-armhf-cross
    - rustup target add armv7-unknown-linux-gnueabihf
    - cargo install cargo-add
    - cargo add openssl
    #-------------------------------------------------AMD64-----------------------------------------------#
    - mkdir -p releases
    - cargo build --release
    - cp target/release/currentcost-influx releases/currentcost-influx-amd64
    #-------------------------------------------------ARM32----------------------------------------------#
    - SRC_DIR=$(pwd)
    - cd /tmp
    - wget https://www.openssl.org/source/openssl-1.1.1d.tar.gz
    - tar xzf openssl-1.1.1d.tar.gz
    - export MACHINE=armv7
    - export ARCH=arm
    - export CC=arm-linux-gnueabihf-gcc
    - cd openssl-1.1.1d && ./config shared && make && cd -
    - export OPENSSL_LIB_DIR=/tmp/openssl-1.1.1d/
    - export OPENSSL_INCLUDE_DIR=/tmp/openssl-1.1.1d/include
    - cd $SRC_DIR
    - cargo build --target=armv7-unknown-linux-gnueabihf --release
    - cp target/armv7-unknown-linux-gnueabihf/release/currentcost-influx releases/currentcost-influx-armv7
    #-------------------------------------------------ARM64----------------------------------------------#
    #- cd /tmp
    #- rm -rf openssl-1.1.1d && tar xzf openssl-1.1.1d.tar.gz
    #- export MACHINE=armv8
    #- export ARCH=armv8-a
    #- export CC=aarch64-linux-gnu-gcc
    #- cd openssl-1.1.1d && ./config shared && make && cd -
    #- cd $SRC_DIR
    #- cargo build --target=aarch64-unknown-linux-gnu --release
    #- cp target/aarch64-unknown-linux-gnu/release/currentcost-influx releases/currentcost-influx-aarch64

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: ./releases/*
  when:
    event: tag    