---
kind: pipeline
name: CurrentCost InfluxDB ARM32 pipeline

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rust:1.40
  environment:
    CARGO_TARGET_ARMV5TE_UNKNOWN_LINUX_GNUEABI_LINKER: arm-linux-gnueabi-gcc
    MACHINE: armv4
    ARCH: arm
    CC: arm-linux-gnueabi-gcc
    OPENSSL_LIB_DIR: /tmp/openssl-1.1.1d/
    OPENSSL_INCLUDE_DIR: /tmp/openssl-1.1.1d/include
  commands:
    - rustup target add armv5te-unknown-linux-gnueabi
    - mkdir -p releases
    - apt-get update
    - apt-get install -y gcc-arm-linux-gnueabi
    - SRC=$(pwd)
    - cd /tmp
    - wget https://www.openssl.org/source/openssl-1.1.1d.tar.gz && tar xzf openssl-1.1.1d.tar.gz && cd openssl-1.1.1d
    - ./config shared && make
    - cd $SRC
    - cargo build --target armv5te-unknown-linux-gnueabi --release
    - cp target/armv5te-unknown-linux-gnueabi/release/currentcost-influx releases/currentcost-influx-arm32

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: ./releases/*
  when:
    event: tag    

---
kind: pipeline
name: CurrentCost InfluxDB AMD64 pipeline

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rust:1.40
  commands:
    - apt-get update
    - apt-get install -y pkg-config libssl-dev
    - mkdir -p releases
    - cargo build --release
    - cp target/release/currentcost-influx releases/currentcost-influx-amd64

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: ./releases/*
  when:
    event: tag    

---
kind: pipeline
name: CurrentCost InfluxDB ARM64 pipeline

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: rust:1.40
  commands:
    - apt-get update
    - apt-get install -y pkg-config libssl-dev
    - mkdir -p releases
    - cargo build --release
    - cp target/release/currentcost-influx releases/currentcost-influx-arm64

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: ./releases/*
  when:
    event: tag    